[tool.ruff]
target-version = "py38"
lint.select = ["E", "F", "I", "UP"]
lint.ignore = ["E501", "E701"] # line too long, multiple statements on one line
src = [".", "utils"]

[tool.ruff.lint.isort]
known-local-folder = ["utils"]

[tool.black]
line-length = 120

[tool.pytest.ini_options]
addopts = "-ra"
pythonpath = ["."]

[tool.coverage.paths]
source = [".", "utils"]

[tool.coverage.report]
show_missing = true



