on:
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-24.04-arm
      env:
        API_URL: ${{secrets.API_URL}}
        API_KEYAUTH: ${{secrets.API_KEYAUTH}}
        API_SECRET: ${{secrets.API_SECRET}}
      steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Install uv
          uses: astral-sh/setup-uv@v7

        - name: Set up Python
          uses: actions/setup-python@v6
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: uv sync

        - name: Run Python Code to that performs ETL from API to DuckDB local file
          run: |
            uv run python main.py
