on:
    workflow_dispatch:
    schedule:
      - cron: '0 */8 * * *'
  
    push:
      # Run when commits are pushed to mainline branch (main or master)
      # Set this to the mainline branch you are using
      branches:
        - main
        - master
  

  
  jobs:
    build:
      runs-on: ubuntu-latest
      env:
        AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
 
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
        - name: Run Python Code to that performs ETL from API to DuckDB local file
          run: |
            python main.py
